name: Generate Snake Animation 🐍

on:
  schedule: # Run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: quantum7coder
          outputs: dist/snake.svg?color_snake=00FF00&color_dots=#0e1116,#00ff00,#00ff00,#00ff00,#00ff00

      - name: Push generated snake.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
